version: '3'

services:
    app-server:
        build: ./docker
        image: tekno-app
        depends_on:
            - mysql
            - redis
        volumes:
            - ./:/application:cached

    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=tekno-app
        volumes:
            - db-data:/var/lib/mysql:cached

    nginx:
        image: nginx:alpine
        ports:
            - "8000:8000"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
            - ./:/application:cached
        depends_on:
            - app-server

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

volumes:
    db-data:
